language: java
jdk: openjdk11
dist: xenial
before_install:
  # Decrypt settings.xml and codesigning.asc which is necessary to deploy to Sonatype Maven Repositories
  - if [ -n "$encrypted_df516d7c6f97_key" ]; then openssl aes-256-cbc -K $encrypted_df516d7c6f97_key -iv $encrypted_df516d7c6f97_iv -in .travis/settings_codesigning.tar.enc -out .travis/settings_codesigning.tar -d; tar xf .travis/settings_codesigning.tar -C .travis; fi
  - if [ -f .travis/codesigning.asc ]; then gpg --fast-import .travis/codesigning.asc; fi
install: true
addons:
  sonarcloud:
    organization: "worksapplications"
    token:
      secure: "VN1PUJ18ZeS2ZN9FFMYIYr4z5qMY7fD1kkJP8WFN9led84i2mo506LzyjTmG//7hNooA3r62k4gBAJIaztsjqGKIPzOnqmZw+XRs7rVl1oReoZ0bbUeGei61srBOVUT7GMe3i5cntj9kt+5M8ieuA5JluwGGeHXNdpKQ0oOPhaEHgBADlxNzSEd8kAM+ynZ6DsMIAjCGQPLqquJTEEk5JG15VxIaTul/ARHypOmjmaTDpqyA4d673dvj9ooPNpUioWYne9k9tQMfGvQaT2gc4GgeG7K4gX0p6ToKRTnLGqohrIvG1fOuvLi1bBUQCiHsaAaaVge7SEvvjc1PFxpeFuDdm+Dhq3l9LmBvIJS3uRM2CGVXyCJtbbjymVbjMOhgzdk+UQKy/W1XqjOrZw45Yt73UAG5gAeULaAOY707sJY2bYXV+xOG7R75e2ndnSqPRJKCLTbBN9nbT0f89Jh+K/41ohLIXlT/xSgAAVBQsLgIfYRbzIMIqAoM5NV8unTLhF/XuWiunbDOSOdfAuUuNVOhlMXFaajISzQtbGEhnOeITyAJk4mszwxK+8E2CqhogRW4Uo0EuHO7VLy8kGf4p1ATJZXPPf9dYRG52/NJQZ4POwuibWsvqYFd1CVgvoklCGxsOrxlctxdNZ2+QTe4Gu8BjiSOkY3lxSF37Nj+pRU="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report -B
after_success:
  - mvn sonar:sonar -B
deploy:
  - provider: script
    script: mvn clean deploy -P release -B --settings .travis/settings.xml
    # Skip cleanup to keep decrepted .travis/settings.xml in workspace
    # https://docs.travis-ci.com/user/deployment/
    skip_cleanup: true
    on:
      branch: develop
cache:
  directories:
    - $HOME/.m2/repository/
